/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAirportsRouteImport } from './routes/_authenticated/airports'
import { Route as AuthenticatedFlightsRouteImport } from './routes/_authenticated/flights'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedAircraftIndexRouteImport } from './routes/_authenticated/aircraft.index'
import { Route as AuthenticatedAircraftIdRouteImport } from './routes/_authenticated/aircraft.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAirportsRoute = AuthenticatedAirportsRouteImport.update({
  id: '/airports',
  path: '/airports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlightsRoute = AuthenticatedFlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAircraftIndexRoute =
  AuthenticatedAircraftIndexRouteImport.update({
    id: '/aircraft/',
    path: '/aircraft/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAircraftIdRoute = AuthenticatedAircraftIdRouteImport.update({
  id: '/aircraft/$id',
  path: '/aircraft/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/airports': typeof AuthenticatedAirportsRoute
  '/flights': typeof AuthenticatedFlightsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/aircraft/$id': typeof AuthenticatedAircraftIdRoute
  '/aircraft/': typeof AuthenticatedAircraftIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/airports': typeof AuthenticatedAirportsRoute
  '/flights': typeof AuthenticatedFlightsRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/aircraft/$id': typeof AuthenticatedAircraftIdRoute
  '/aircraft': typeof AuthenticatedAircraftIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/airports': typeof AuthenticatedAirportsRoute
  '/_authenticated/flights': typeof AuthenticatedFlightsRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/aircraft/$id': typeof AuthenticatedAircraftIdRoute
  '/_authenticated/aircraft/': typeof AuthenticatedAircraftIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/airports'
    | '/flights'
    | '/plan'
    | '/aircraft/$id'
    | '/aircraft/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/airports'
    | '/flights'
    | '/plan'
    | '/aircraft/$id'
    | '/aircraft'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/airports'
    | '/_authenticated/flights'
    | '/_authenticated/plan'
    | '/_authenticated/aircraft/$id'
    | '/_authenticated/aircraft/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/airports': {
      id: '/_authenticated/airports'
      path: '/airports'
      fullPath: '/airports'
      preLoaderRoute: typeof AuthenticatedAirportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flights': {
      id: '/_authenticated/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof AuthenticatedFlightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aircraft/': {
      id: '/_authenticated/aircraft/'
      path: '/aircraft'
      fullPath: '/aircraft/'
      preLoaderRoute: typeof AuthenticatedAircraftIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aircraft/$id': {
      id: '/_authenticated/aircraft/$id'
      path: '/aircraft/$id'
      fullPath: '/aircraft/$id'
      preLoaderRoute: typeof AuthenticatedAircraftIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAirportsRoute: typeof AuthenticatedAirportsRoute
  AuthenticatedFlightsRoute: typeof AuthenticatedFlightsRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedAircraftIdRoute: typeof AuthenticatedAircraftIdRoute
  AuthenticatedAircraftIndexRoute: typeof AuthenticatedAircraftIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAirportsRoute: AuthenticatedAirportsRoute,
  AuthenticatedFlightsRoute: AuthenticatedFlightsRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedAircraftIdRoute: AuthenticatedAircraftIdRoute,
  AuthenticatedAircraftIndexRoute: AuthenticatedAircraftIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
